/**
 *
 *  ESUP-Portail ESUP-MONDOSSIERWEB-PEGASE - Copyright (c) 2021 ESUP-Portail consortium
 *
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/*
 * API CHC v5
 * Liste l'ensemble des services et des opérations disponibles dans le module choix des cursus v5 
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.chc;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;

/**
 * Nomenclature
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-27T10:38:20.872+02:00[Europe/Paris]")

public class Nomenclature {
  public static final String SERIALIZED_NAME_TYPE_NOMENCLATURE = "typeNomenclature";
  @SerializedName(SERIALIZED_NAME_TYPE_NOMENCLATURE)
  protected String typeNomenclature;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_LIBELLE_COURT = "libelleCourt";
  @SerializedName(SERIALIZED_NAME_LIBELLE_COURT)
  private String libelleCourt;

  public static final String SERIALIZED_NAME_LIBELLE_LONG = "libelleLong";
  @SerializedName(SERIALIZED_NAME_LIBELLE_LONG)
  private String libelleLong;

  public static final String SERIALIZED_NAME_LIBELLE_AFFICHAGE = "libelleAffichage";
  @SerializedName(SERIALIZED_NAME_LIBELLE_AFFICHAGE)
  private String libelleAffichage;

  public static final String SERIALIZED_NAME_PRIORITE_AFFICHAGE = "prioriteAffichage";
  @SerializedName(SERIALIZED_NAME_PRIORITE_AFFICHAGE)
  private Integer prioriteAffichage;

  public static final String SERIALIZED_NAME_DATE_DEBUT_VALIDITE = "dateDebutValidite";
  @SerializedName(SERIALIZED_NAME_DATE_DEBUT_VALIDITE)
  private LocalDate dateDebutValidite;

  public static final String SERIALIZED_NAME_DATE_FIN_VALIDITE = "dateFinValidite";
  @SerializedName(SERIALIZED_NAME_DATE_FIN_VALIDITE)
  private LocalDate dateFinValidite;

  public static final String SERIALIZED_NAME_TEMOIN_VISIBLE = "temoinVisible";
  @SerializedName(SERIALIZED_NAME_TEMOIN_VISIBLE)
  private Boolean temoinVisible;

  public static final String SERIALIZED_NAME_TEMOIN_LIVRE = "temoinLivre";
  @SerializedName(SERIALIZED_NAME_TEMOIN_LIVRE)
  private Boolean temoinLivre;

  public Nomenclature() {
    this.typeNomenclature = this.getClass().getSimpleName();
  }

  public Nomenclature typeNomenclature(String typeNomenclature) {
    
    this.typeNomenclature = typeNomenclature;
    return this;
  }

   /**
   * Discriminant
   * @return typeNomenclature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Discriminant")

  public String getTypeNomenclature() {
    return typeNomenclature;
  }


  public void setTypeNomenclature(String typeNomenclature) {
    this.typeNomenclature = typeNomenclature;
  }


  public Nomenclature code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Code interne de la nomenclature choisi par l&#39;établissement
   * @return code
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code interne de la nomenclature choisi par l'établissement")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public Nomenclature libelleCourt(String libelleCourt) {
    
    this.libelleCourt = libelleCourt;
    return this;
  }

   /**
   * Libelle court de la nomenclature
   * @return libelleCourt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Libelle court de la nomenclature")

  public String getLibelleCourt() {
    return libelleCourt;
  }


  public void setLibelleCourt(String libelleCourt) {
    this.libelleCourt = libelleCourt;
  }


  public Nomenclature libelleLong(String libelleLong) {
    
    this.libelleLong = libelleLong;
    return this;
  }

   /**
   * Nom complet de la nomenclature
   * @return libelleLong
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Nom complet de la nomenclature")

  public String getLibelleLong() {
    return libelleLong;
  }


  public void setLibelleLong(String libelleLong) {
    this.libelleLong = libelleLong;
  }


  public Nomenclature libelleAffichage(String libelleAffichage) {
    
    this.libelleAffichage = libelleAffichage;
    return this;
  }

   /**
   * Libellé qui sera affiché aux usagers pour les fonctionnalités à distance
   * @return libelleAffichage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Libellé qui sera affiché aux usagers pour les fonctionnalités à distance")

  public String getLibelleAffichage() {
    return libelleAffichage;
  }


  public void setLibelleAffichage(String libelleAffichage) {
    this.libelleAffichage = libelleAffichage;
  }


  public Nomenclature prioriteAffichage(Integer prioriteAffichage) {
    
    this.prioriteAffichage = prioriteAffichage;
    return this;
  }

   /**
   * Plus le nombre est élevé plus il apparaît en priorité dans la liste de valeurs
   * @return prioriteAffichage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Plus le nombre est élevé plus il apparaît en priorité dans la liste de valeurs")

  public Integer getPrioriteAffichage() {
    return prioriteAffichage;
  }


  public void setPrioriteAffichage(Integer prioriteAffichage) {
    this.prioriteAffichage = prioriteAffichage;
  }


  public Nomenclature dateDebutValidite(LocalDate dateDebutValidite) {
    
    this.dateDebutValidite = dateDebutValidite;
    return this;
  }

   /**
   * Date du début de la validité de la nomenclature
   * @return dateDebutValidite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date du début de la validité de la nomenclature")

  public LocalDate getDateDebutValidite() {
    return dateDebutValidite;
  }


  public void setDateDebutValidite(LocalDate dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
  }


  public Nomenclature dateFinValidite(LocalDate dateFinValidite) {
    
    this.dateFinValidite = dateFinValidite;
    return this;
  }

   /**
   * Date de la fin de la validité de la nomenclature
   * @return dateFinValidite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date de la fin de la validité de la nomenclature")

  public LocalDate getDateFinValidite() {
    return dateFinValidite;
  }


  public void setDateFinValidite(LocalDate dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
  }


  public Nomenclature temoinVisible(Boolean temoinVisible) {
    
    this.temoinVisible = temoinVisible;
    return this;
  }

   /**
   * Témoin de la visibilité de la nomenclature
   * @return temoinVisible
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Témoin de la visibilité de la nomenclature")

  public Boolean getTemoinVisible() {
    return temoinVisible;
  }


  public void setTemoinVisible(Boolean temoinVisible) {
    this.temoinVisible = temoinVisible;
  }


  public Nomenclature temoinLivre(Boolean temoinLivre) {
    
    this.temoinLivre = temoinLivre;
    return this;
  }

   /**
   * Témoin indiquant si la nomenclature a été livrée
   * @return temoinLivre
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Témoin indiquant si la nomenclature a été livrée")

  public Boolean getTemoinLivre() {
    return temoinLivre;
  }


  public void setTemoinLivre(Boolean temoinLivre) {
    this.temoinLivre = temoinLivre;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Nomenclature nomenclature = (Nomenclature) o;
    return Objects.equals(this.typeNomenclature, nomenclature.typeNomenclature) &&
        Objects.equals(this.code, nomenclature.code) &&
        Objects.equals(this.libelleCourt, nomenclature.libelleCourt) &&
        Objects.equals(this.libelleLong, nomenclature.libelleLong) &&
        Objects.equals(this.libelleAffichage, nomenclature.libelleAffichage) &&
        Objects.equals(this.prioriteAffichage, nomenclature.prioriteAffichage) &&
        Objects.equals(this.dateDebutValidite, nomenclature.dateDebutValidite) &&
        Objects.equals(this.dateFinValidite, nomenclature.dateFinValidite) &&
        Objects.equals(this.temoinVisible, nomenclature.temoinVisible) &&
        Objects.equals(this.temoinLivre, nomenclature.temoinLivre);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typeNomenclature, code, libelleCourt, libelleLong, libelleAffichage, prioriteAffichage, dateDebutValidite, dateFinValidite, temoinVisible, temoinLivre);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Nomenclature {\n");
    sb.append("    typeNomenclature: ").append(toIndentedString(typeNomenclature)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    libelleCourt: ").append(toIndentedString(libelleCourt)).append("\n");
    sb.append("    libelleLong: ").append(toIndentedString(libelleLong)).append("\n");
    sb.append("    libelleAffichage: ").append(toIndentedString(libelleAffichage)).append("\n");
    sb.append("    prioriteAffichage: ").append(toIndentedString(prioriteAffichage)).append("\n");
    sb.append("    dateDebutValidite: ").append(toIndentedString(dateDebutValidite)).append("\n");
    sb.append("    dateFinValidite: ").append(toIndentedString(dateFinValidite)).append("\n");
    sb.append("    temoinVisible: ").append(toIndentedString(temoinVisible)).append("\n");
    sb.append("    temoinLivre: ").append(toIndentedString(temoinLivre)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

