/**
 *
 *  ESUP-Portail ESUP-MONDOSSIERWEB-PEGASE - Copyright (c) 2021 ESUP-Portail consortium
 *
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/*
 * API CHC v5
 * Liste l'ensemble des services et des opérations disponibles dans le module choix des cursus v5 
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.chc;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.univlorraine.pegase.model.chc.ParametrageKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ObjetMaquetteKeyExtension
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-27T10:38:20.872+02:00[Europe/Paris]")
public class ObjetMaquetteKeyExtension {
  public static final String SERIALIZED_NAME_CODE_CHEMIN = "codeChemin";
  @SerializedName(SERIALIZED_NAME_CODE_CHEMIN)
  private String codeChemin;

  public static final String SERIALIZED_NAME_CODE_PERIODE = "codePeriode";
  @SerializedName(SERIALIZED_NAME_CODE_PERIODE)
  private String codePeriode;

  public static final String SERIALIZED_NAME_CODE_STRUCTURE = "codeStructure";
  @SerializedName(SERIALIZED_NAME_CODE_STRUCTURE)
  private String codeStructure;

  public static final String SERIALIZED_NAME_TEMOIN_AFFECTE = "temoinAffecte";
  @SerializedName(SERIALIZED_NAME_TEMOIN_AFFECTE)
  private Boolean temoinAffecte;

  public static final String SERIALIZED_NAME_TEMOIN_ACQUIS = "temoinAcquis";
  @SerializedName(SERIALIZED_NAME_TEMOIN_ACQUIS)
  private Boolean temoinAcquis;

  public static final String SERIALIZED_NAME_TYPE_AMENAGEMENT_LST = "typeAmenagementLst";
  @SerializedName(SERIALIZED_NAME_TYPE_AMENAGEMENT_LST)
  private List<ParametrageKey> typeAmenagementLst = null;


  public ObjetMaquetteKeyExtension codeChemin(String codeChemin) {
    
    this.codeChemin = codeChemin;
    return this;
  }

   /**
   * Le code chemin de l&#39;objet maquette - identifiant unique
   * @return codeChemin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code chemin de l'objet maquette - identifiant unique")

  public String getCodeChemin() {
    return codeChemin;
  }


  public void setCodeChemin(String codeChemin) {
    this.codeChemin = codeChemin;
  }


  public ObjetMaquetteKeyExtension codePeriode(String codePeriode) {
    
    this.codePeriode = codePeriode;
    return this;
  }

   /**
   * Le code de la période  - identifiant unique
   * @return codePeriode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code de la période  - identifiant unique")

  public String getCodePeriode() {
    return codePeriode;
  }


  public void setCodePeriode(String codePeriode) {
    this.codePeriode = codePeriode;
  }


  public ObjetMaquetteKeyExtension codeStructure(String codeStructure) {
    
    this.codeStructure = codeStructure;
    return this;
  }

   /**
   * Le code structure  - identifiant unique
   * @return codeStructure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code structure  - identifiant unique")

  public String getCodeStructure() {
    return codeStructure;
  }


  public void setCodeStructure(String codeStructure) {
    this.codeStructure = codeStructure;
  }


  public ObjetMaquetteKeyExtension temoinAffecte(Boolean temoinAffecte) {
    
    this.temoinAffecte = temoinAffecte;
    return this;
  }

   /**
   * Est ce que l&#39;apprenant est affecté sur l&#39;objet maquette?
   * @return temoinAffecte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Est ce que l'apprenant est affecté sur l'objet maquette?")

  public Boolean getTemoinAffecte() {
    return temoinAffecte;
  }


  public void setTemoinAffecte(Boolean temoinAffecte) {
    this.temoinAffecte = temoinAffecte;
  }


  public ObjetMaquetteKeyExtension temoinAcquis(Boolean temoinAcquis) {
    
    this.temoinAcquis = temoinAcquis;
    return this;
  }

   /**
   * Est ce que l&#39;apprenant a validé son cursus sur l&#39;objet maquette?
   * @return temoinAcquis
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Est ce que l'apprenant a validé son cursus sur l'objet maquette?")

  public Boolean getTemoinAcquis() {
    return temoinAcquis;
  }


  public void setTemoinAcquis(Boolean temoinAcquis) {
    this.temoinAcquis = temoinAcquis;
  }


  public ObjetMaquetteKeyExtension typeAmenagementLst(List<ParametrageKey> typeAmenagementLst) {
    
    this.typeAmenagementLst = typeAmenagementLst;
    return this;
  }

  public ObjetMaquetteKeyExtension addTypeAmenagementLstItem(ParametrageKey typeAmenagementLstItem) {
    if (this.typeAmenagementLst == null) {
      this.typeAmenagementLst = new ArrayList<>();
    }
    this.typeAmenagementLst.add(typeAmenagementLstItem);
    return this;
  }

   /**
   * Get typeAmenagementLst
   * @return typeAmenagementLst
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ParametrageKey> getTypeAmenagementLst() {
    return typeAmenagementLst;
  }


  public void setTypeAmenagementLst(List<ParametrageKey> typeAmenagementLst) {
    this.typeAmenagementLst = typeAmenagementLst;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ObjetMaquetteKeyExtension objetMaquetteKeyExtension = (ObjetMaquetteKeyExtension) o;
    return Objects.equals(this.codeChemin, objetMaquetteKeyExtension.codeChemin) &&
        Objects.equals(this.codePeriode, objetMaquetteKeyExtension.codePeriode) &&
        Objects.equals(this.codeStructure, objetMaquetteKeyExtension.codeStructure) &&
        Objects.equals(this.temoinAffecte, objetMaquetteKeyExtension.temoinAffecte) &&
        Objects.equals(this.temoinAcquis, objetMaquetteKeyExtension.temoinAcquis) &&
        Objects.equals(this.typeAmenagementLst, objetMaquetteKeyExtension.typeAmenagementLst);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeChemin, codePeriode, codeStructure, temoinAffecte, temoinAcquis, typeAmenagementLst);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ObjetMaquetteKeyExtension {\n");
    sb.append("    codeChemin: ").append(toIndentedString(codeChemin)).append("\n");
    sb.append("    codePeriode: ").append(toIndentedString(codePeriode)).append("\n");
    sb.append("    codeStructure: ").append(toIndentedString(codeStructure)).append("\n");
    sb.append("    temoinAffecte: ").append(toIndentedString(temoinAffecte)).append("\n");
    sb.append("    temoinAcquis: ").append(toIndentedString(temoinAcquis)).append("\n");
    sb.append("    typeAmenagementLst: ").append(toIndentedString(typeAmenagementLst)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

