/**
 *
 *  ESUP-Portail ESUP-MONDOSSIERWEB-PEGASE - Copyright (c) 2021 ESUP-Portail consortium
 *
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */
/*
 * API CHC v5
 * Liste l'ensemble des services et des opérations disponibles dans le module choix des cursus v5 
 *
 * The version of the OpenAPI document: 5.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.chc;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.univlorraine.pegase.model.chc.ApprenantKeyExtention;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ParamsCursusApprenants
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-27T10:38:20.872+02:00[Europe/Paris]")
public class ParamsCursusApprenants {
  public static final String SERIALIZED_NAME_APPRENANT_LST = "apprenantLst";
  @SerializedName(SERIALIZED_NAME_APPRENANT_LST)
  private List<ApprenantKeyExtention> apprenantLst = null;

  public static final String SERIALIZED_NAME_CODE_CHEMIN = "codeChemin";
  @SerializedName(SERIALIZED_NAME_CODE_CHEMIN)
  private String codeChemin;

  public static final String SERIALIZED_NAME_CODE_PERIODE = "codePeriode";
  @SerializedName(SERIALIZED_NAME_CODE_PERIODE)
  private String codePeriode;

  public static final String SERIALIZED_NAME_CODE_STRUCTURE = "codeStructure";
  @SerializedName(SERIALIZED_NAME_CODE_STRUCTURE)
  private String codeStructure;

  public static final String SERIALIZED_NAME_TEMOIN_DESCENDANT = "temoinDescendant";
  @SerializedName(SERIALIZED_NAME_TEMOIN_DESCENDANT)
  private Boolean temoinDescendant;


  public ParamsCursusApprenants apprenantLst(List<ApprenantKeyExtention> apprenantLst) {
    
    this.apprenantLst = apprenantLst;
    return this;
  }

  public ParamsCursusApprenants addApprenantLstItem(ApprenantKeyExtention apprenantLstItem) {
    if (this.apprenantLst == null) {
      this.apprenantLst = new ArrayList<>();
    }
    this.apprenantLst.add(apprenantLstItem);
    return this;
  }

   /**
   * Get apprenantLst
   * @return apprenantLst
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ApprenantKeyExtention> getApprenantLst() {
    return apprenantLst;
  }


  public void setApprenantLst(List<ApprenantKeyExtention> apprenantLst) {
    this.apprenantLst = apprenantLst;
  }


  public ParamsCursusApprenants codeChemin(String codeChemin) {
    
    this.codeChemin = codeChemin;
    return this;
  }

   /**
   * le code du chemin de l&#39;objet maquette (une formation ou un objet de formation)
   * @return codeChemin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "le code du chemin de l'objet maquette (une formation ou un objet de formation)")

  public String getCodeChemin() {
    return codeChemin;
  }


  public void setCodeChemin(String codeChemin) {
    this.codeChemin = codeChemin;
  }


  public ParamsCursusApprenants codePeriode(String codePeriode) {
    
    this.codePeriode = codePeriode;
    return this;
  }

   /**
   * le code de la période
   * @return codePeriode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "le code de la période")

  public String getCodePeriode() {
    return codePeriode;
  }


  public void setCodePeriode(String codePeriode) {
    this.codePeriode = codePeriode;
  }


  public ParamsCursusApprenants codeStructure(String codeStructure) {
    
    this.codeStructure = codeStructure;
    return this;
  }

   /**
   * le code de la structure
   * @return codeStructure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "le code de la structure")

  public String getCodeStructure() {
    return codeStructure;
  }


  public void setCodeStructure(String codeStructure) {
    this.codeStructure = codeStructure;
  }


  public ParamsCursusApprenants temoinDescendant(Boolean temoinDescendant) {
    
    this.temoinDescendant = temoinDescendant;
    return this;
  }

   /**
   * Est ce que l&#39;affectation se fait sur les descendants directs?
   * @return temoinDescendant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Est ce que l'affectation se fait sur les descendants directs?")

  public Boolean getTemoinDescendant() {
    return temoinDescendant;
  }


  public void setTemoinDescendant(Boolean temoinDescendant) {
    this.temoinDescendant = temoinDescendant;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParamsCursusApprenants paramsCursusApprenants = (ParamsCursusApprenants) o;
    return Objects.equals(this.apprenantLst, paramsCursusApprenants.apprenantLst) &&
        Objects.equals(this.codeChemin, paramsCursusApprenants.codeChemin) &&
        Objects.equals(this.codePeriode, paramsCursusApprenants.codePeriode) &&
        Objects.equals(this.codeStructure, paramsCursusApprenants.codeStructure) &&
        Objects.equals(this.temoinDescendant, paramsCursusApprenants.temoinDescendant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apprenantLst, codeChemin, codePeriode, codeStructure, temoinDescendant);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParamsCursusApprenants {\n");
    sb.append("    apprenantLst: ").append(toIndentedString(apprenantLst)).append("\n");
    sb.append("    codeChemin: ").append(toIndentedString(codeChemin)).append("\n");
    sb.append("    codePeriode: ").append(toIndentedString(codePeriode)).append("\n");
    sb.append("    codeStructure: ").append(toIndentedString(codeStructure)).append("\n");
    sb.append("    temoinDescendant: ").append(toIndentedString(temoinDescendant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

