workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "toto"

include:
  - project: 'dn-sied/ci-config'
    file: '/.gitlab-ci-template-container-image.yml'

variables:
  MAVEN_IMAGE: maven:3.9.10-eclipse-temurin-21-alpine
  MAVEN_ADDITIONAL_CLI_OPTS: "-Pcoverage,production -Dmaven.test.skip=true"

⚙️ verify:
  before_script:
    - cat ${TEST_APPLICATION_PROPERTIES} > ${CI_PROJECT_DIR}/src/test/resources/test.properties
    - cat ${CI_PROJECT_DIR}/src/test/resources/test.properties
  when: manual

# *** Version Kaniko ***
#🚀 container image:
#  when: manual

# *** Version BuildKit rootless ***
🚀 container image:
  stage: 📦 Build
  needs:
    - job: ⚙️ version
      artifacts: true
    #- job: ⚙️ verify
    #  optional: true
    #- job: 🛡️ sonarqube
    #  optional: true
  image:
    name: moby/buildkit:rootless
    entrypoint: [""]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script: # Informations de connexion au registry Harbor dans la conf Docker
    - mkdir -p ~/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(printf "%s:%s" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" | base64 | tr -d '\n')\"}}}" > ~/.docker/config.json
  script:
    # Build de l'image docker et push sur harbor
    - >-
      buildctl-daemonless.sh build
      --frontend=dockerfile.v0
      --local context="${CI_PROJECT_DIR}"
      --local dockerfile="${CI_PROJECT_DIR}"
      --output type=image,name="${CI_REGISTRY_IMAGE}:${BUILD_VERSION}",push=true
  when: manual    
