version: "3.7"

services:

  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: mariadb
    volumes:
      - ./.docker/mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE:  mdwpegase

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: mypass
    depends_on:
      - mariadb
      
  mdw-pegase:
    #image: registry.univ.fr/esup-mdw-pegase:2.2.2
    image: esup-mdw-pegase:2.2.2
    restart: always
    container_name: mdw-pegase
    ports:
      - 8080:8080
    volumes:
      - ./.docker/esup-mdw-pegase:/config
    environment:
      JAVA_OPTS: -Dspring.config.location=file:/config/application.properties
    depends_on:
      - mariadb
