version: "3.7"

services:
      
  mdw-pegase:
    #image: registry.univ.fr/esup-mdw-pegase:1.0.5
    image: esup-mdw-pegase:1.0.5
    restart: always
    container_name: mdw-pegase_mdw-pegase
    ports:
      - 8080:8080
    volumes:
      - ./.docker/esup-mdw-pegase:/config
    networks:
      - mdw-network
    environment:
      JAVA_OPTS: -Dspring.config.location=file:/config/application.properties

networks:
    mdw-network:
        external:
            name: mdw-network
