version: "3.7"

services:

  php:
    image: php:7.2-fpm
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    container_name: mariadb_php
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    restart: always
    container_name: mariadb_mariadb
    volumes:
      - ./.docker/mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mypass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mariadb_phpmyadmin
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
      
  mdw-pegase:
    #image: registry.univ.fr/esup-mdw-pegase:1.0.5
    image: esup-mdw-pegase:1.5.1
    restart: always
    container_name: mdw-pegase_mdw-pegase
    ports:
      - 8080:8080
    volumes:
      - ./.docker/esup-mdw-pegase:/config
    environment:
      JAVA_OPTS: -Dspring.config.location=file:/config/application.properties
    depends_on:
      - mariadb

