/*
 * Swagger Gestion - INS
 * Il s'agit de l'API de gestion - INS.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.insgestion;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import fr.univlorraine.pegase.model.insgestion.ContactComplet;
import fr.univlorraine.pegase.model.insgestion.DemandeDeContactSimple;
import fr.univlorraine.pegase.model.insgestion.VueContactAdresseAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ContactAdresseComplet
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-07-17T14:31:10.718+02:00[Europe/Paris]")
public class ContactAdresseComplet extends ContactComplet {
  public static final String SERIALIZED_NAME_PAYS = "pays";
  @SerializedName(SERIALIZED_NAME_PAYS)
  private String pays;

  public static final String SERIALIZED_NAME_LIGNE1_OU_ETAGE = "ligne1OuEtage";
  @SerializedName(SERIALIZED_NAME_LIGNE1_OU_ETAGE)
  private String ligne1OuEtage;

  public static final String SERIALIZED_NAME_LIGNE2_OU_BATIMENT = "ligne2OuBatiment";
  @SerializedName(SERIALIZED_NAME_LIGNE2_OU_BATIMENT)
  private String ligne2OuBatiment;

  public static final String SERIALIZED_NAME_LIGNE3_OU_VOIE = "ligne3OuVoie";
  @SerializedName(SERIALIZED_NAME_LIGNE3_OU_VOIE)
  private String ligne3OuVoie;

  public static final String SERIALIZED_NAME_LIGNE4_OU_COMPLEMENT = "ligne4OuComplement";
  @SerializedName(SERIALIZED_NAME_LIGNE4_OU_COMPLEMENT)
  private String ligne4OuComplement;

  public static final String SERIALIZED_NAME_LIGNE5_ETRANGER = "ligne5Etranger";
  @SerializedName(SERIALIZED_NAME_LIGNE5_ETRANGER)
  private String ligne5Etranger;

  public static final String SERIALIZED_NAME_CODE_POSTAL = "codePostal";
  @SerializedName(SERIALIZED_NAME_CODE_POSTAL)
  private String codePostal;

  public static final String SERIALIZED_NAME_COMMUNE = "commune";
  @SerializedName(SERIALIZED_NAME_COMMUNE)
  private String commune;


  public ContactAdresseComplet pays(String pays) {
    
    this.pays = pays;
    return this;
  }

   /**
   * Code INSEE du pays (100 pour la France, sinon l&#39;adresse est à l&#39;étranger)
   * @return pays
  **/
  @ApiModelProperty(required = true, value = "Code INSEE du pays (100 pour la France, sinon l'adresse est à l'étranger)")

  public String getPays() {
    return pays;
  }


  public void setPays(String pays) {
    this.pays = pays;
  }


  public ContactAdresseComplet ligne1OuEtage(String ligne1OuEtage) {
    
    this.ligne1OuEtage = ligne1OuEtage;
    return this;
  }

   /**
   * Le n°app/étage/couloir/esc/chez ou ligne 1 de l&#39;adresse étrangère
   * @return ligne1OuEtage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le n°app/étage/couloir/esc/chez ou ligne 1 de l'adresse étrangère")

  public String getLigne1OuEtage() {
    return ligne1OuEtage;
  }


  public void setLigne1OuEtage(String ligne1OuEtage) {
    this.ligne1OuEtage = ligne1OuEtage;
  }


  public ContactAdresseComplet ligne2OuBatiment(String ligne2OuBatiment) {
    
    this.ligne2OuBatiment = ligne2OuBatiment;
    return this;
  }

   /**
   * L&#39;entrée/bâtiment/immeuble/résidence ou ligne 2 de l&#39;adresse étrangère
   * @return ligne2OuBatiment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "L'entrée/bâtiment/immeuble/résidence ou ligne 2 de l'adresse étrangère")

  public String getLigne2OuBatiment() {
    return ligne2OuBatiment;
  }


  public void setLigne2OuBatiment(String ligne2OuBatiment) {
    this.ligne2OuBatiment = ligne2OuBatiment;
  }


  public ContactAdresseComplet ligne3OuVoie(String ligne3OuVoie) {
    
    this.ligne3OuVoie = ligne3OuVoie;
    return this;
  }

   /**
   * Le numéro et le libellé de la voie ou ligne 3 de l&#39;adresse étrangère
   * @return ligne3OuVoie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le numéro et le libellé de la voie ou ligne 3 de l'adresse étrangère")

  public String getLigne3OuVoie() {
    return ligne3OuVoie;
  }


  public void setLigne3OuVoie(String ligne3OuVoie) {
    this.ligne3OuVoie = ligne3OuVoie;
  }


  public ContactAdresseComplet ligne4OuComplement(String ligne4OuComplement) {
    
    this.ligne4OuComplement = ligne4OuComplement;
    return this;
  }

   /**
   * Le lieu-dit ou service particulier de distribution ou ligne 4 de l&#39;adresse étrangère
   * @return ligne4OuComplement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le lieu-dit ou service particulier de distribution ou ligne 4 de l'adresse étrangère")

  public String getLigne4OuComplement() {
    return ligne4OuComplement;
  }


  public void setLigne4OuComplement(String ligne4OuComplement) {
    this.ligne4OuComplement = ligne4OuComplement;
  }


  public ContactAdresseComplet ligne5Etranger(String ligne5Etranger) {
    
    this.ligne5Etranger = ligne5Etranger;
    return this;
  }

   /**
   * Ligne 5 de l&#39;adresse étrangère (vide si adresse en France)
   * @return ligne5Etranger
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne 5 de l'adresse étrangère (vide si adresse en France)")

  public String getLigne5Etranger() {
    return ligne5Etranger;
  }


  public void setLigne5Etranger(String ligne5Etranger) {
    this.ligne5Etranger = ligne5Etranger;
  }


  public ContactAdresseComplet codePostal(String codePostal) {
    
    this.codePostal = codePostal;
    return this;
  }

   /**
   * Le code postal de l&#39;adresse en France (vide si adresse étrangère)
   * @return codePostal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code postal de l'adresse en France (vide si adresse étrangère)")

  public String getCodePostal() {
    return codePostal;
  }


  public void setCodePostal(String codePostal) {
    this.codePostal = codePostal;
  }


  public ContactAdresseComplet commune(String commune) {
    
    this.commune = commune;
    return this;
  }

   /**
   * Le code INSEE de la commune de l&#39;adresse en France (vide si adresse étrangère)
   * @return commune
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le code INSEE de la commune de l'adresse en France (vide si adresse étrangère)")

  public String getCommune() {
    return commune;
  }


  public void setCommune(String commune) {
    this.commune = commune;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactAdresseComplet contactAdresseComplet = (ContactAdresseComplet) o;
    return Objects.equals(this.pays, contactAdresseComplet.pays) &&
        Objects.equals(this.ligne1OuEtage, contactAdresseComplet.ligne1OuEtage) &&
        Objects.equals(this.ligne2OuBatiment, contactAdresseComplet.ligne2OuBatiment) &&
        Objects.equals(this.ligne3OuVoie, contactAdresseComplet.ligne3OuVoie) &&
        Objects.equals(this.ligne4OuComplement, contactAdresseComplet.ligne4OuComplement) &&
        Objects.equals(this.ligne5Etranger, contactAdresseComplet.ligne5Etranger) &&
        Objects.equals(this.codePostal, contactAdresseComplet.codePostal) &&
        Objects.equals(this.commune, contactAdresseComplet.commune) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pays, ligne1OuEtage, ligne2OuBatiment, ligne3OuVoie, ligne4OuComplement, ligne5Etranger, codePostal, commune, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactAdresseComplet {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    pays: ").append(toIndentedString(pays)).append("\n");
    sb.append("    ligne1OuEtage: ").append(toIndentedString(ligne1OuEtage)).append("\n");
    sb.append("    ligne2OuBatiment: ").append(toIndentedString(ligne2OuBatiment)).append("\n");
    sb.append("    ligne3OuVoie: ").append(toIndentedString(ligne3OuVoie)).append("\n");
    sb.append("    ligne4OuComplement: ").append(toIndentedString(ligne4OuComplement)).append("\n");
    sb.append("    ligne5Etranger: ").append(toIndentedString(ligne5Etranger)).append("\n");
    sb.append("    codePostal: ").append(toIndentedString(codePostal)).append("\n");
    sb.append("    commune: ").append(toIndentedString(commune)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

