/*
 * Swagger Gestion - INS
 * Il s'agit de l'API de gestion - INS.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.insgestion;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * ModaliteDePaiement
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-05-27T10:35:31.587+02:00[Europe/Paris]")
public class ModaliteDePaiement {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_CODE_STRUCTURE = "codeStructure";
  @SerializedName(SERIALIZED_NAME_CODE_STRUCTURE)
  private String codeStructure;

  public static final String SERIALIZED_NAME_LIBELLE_AFFICHAGE = "libelleAffichage";
  @SerializedName(SERIALIZED_NAME_LIBELLE_AFFICHAGE)
  private String libelleAffichage;

  public static final String SERIALIZED_NAME_CODE_MODE_DE_PAIEMENT = "codeModeDePaiement";
  @SerializedName(SERIALIZED_NAME_CODE_MODE_DE_PAIEMENT)
  private String codeModeDePaiement;

  public static final String SERIALIZED_NAME_TEMOIN_VISIBLE_ETUDIANT = "temoinVisibleEtudiant";
  @SerializedName(SERIALIZED_NAME_TEMOIN_VISIBLE_ETUDIANT)
  private Boolean temoinVisibleEtudiant;

  /**
   * Statut du paiement généré à la confirmation du paiement
   */
  @JsonAdapter(StatutPaiementEnum.Adapter.class)
  public enum StatutPaiementEnum {
    NON_PAYE("non_paye"),
    
    EN_ATTENTE("en_attente"),
    
    PAYE("paye"),
    
    VALIDE("valide");

    private String value;

    StatutPaiementEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatutPaiementEnum fromValue(String value) {
      for (StatutPaiementEnum b : StatutPaiementEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<StatutPaiementEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatutPaiementEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatutPaiementEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return StatutPaiementEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_STATUT_PAIEMENT = "statutPaiement";
  @SerializedName(SERIALIZED_NAME_STATUT_PAIEMENT)
  private StatutPaiementEnum statutPaiement;

  public static final String SERIALIZED_NAME_TEMOIN_PRIMO = "temoinPrimo";
  @SerializedName(SERIALIZED_NAME_TEMOIN_PRIMO)
  private Boolean temoinPrimo;

  public static final String SERIALIZED_NAME_TEMOIN_REINS = "temoinReins";
  @SerializedName(SERIALIZED_NAME_TEMOIN_REINS)
  private Boolean temoinReins;

  public static final String SERIALIZED_NAME_NOMBRE_DE_PAIEMENTS = "nombreDePaiements";
  @SerializedName(SERIALIZED_NAME_NOMBRE_DE_PAIEMENTS)
  private Integer nombreDePaiements = 1;

  public static final String SERIALIZED_NAME_MONTANT_MINIMUM = "montantMinimum";
  @SerializedName(SERIALIZED_NAME_MONTANT_MINIMUM)
  private BigDecimal montantMinimum;

  public static final String SERIALIZED_NAME_MONTANT_MAXIMUM = "montantMaximum";
  @SerializedName(SERIALIZED_NAME_MONTANT_MAXIMUM)
  private BigDecimal montantMaximum;

  public static final String SERIALIZED_NAME_TEMOIN_SAISIE_REFERENCE = "temoinSaisieReference";
  @SerializedName(SERIALIZED_NAME_TEMOIN_SAISIE_REFERENCE)
  private Boolean temoinSaisieReference;

  public static final String SERIALIZED_NAME_TEMOIN_PAIEMENT_EN_LIGNE = "temoinPaiementEnLigne";
  @SerializedName(SERIALIZED_NAME_TEMOIN_PAIEMENT_EN_LIGNE)
  private Boolean temoinPaiementEnLigne;

  public static final String SERIALIZED_NAME_DATE_DEBUT_VALIDITE = "dateDebutValidite";
  @SerializedName(SERIALIZED_NAME_DATE_DEBUT_VALIDITE)
  private String dateDebutValidite;

  public static final String SERIALIZED_NAME_DATE_FIN_VALIDITE = "dateFinValidite";
  @SerializedName(SERIALIZED_NAME_DATE_FIN_VALIDITE)
  private String dateFinValidite;

  public static final String SERIALIZED_NAME_PRIORITE_AFFICHAGE = "prioriteAffichage";
  @SerializedName(SERIALIZED_NAME_PRIORITE_AFFICHAGE)
  private Integer prioriteAffichage = 0;

  public static final String SERIALIZED_NAME_NOTICE = "notice";
  @SerializedName(SERIALIZED_NAME_NOTICE)
  private String notice;


  public ModaliteDePaiement code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Le code metier en saisie libre
   * @return code
  **/
  @ApiModelProperty(required = true, value = "Le code metier en saisie libre")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public ModaliteDePaiement codeStructure(String codeStructure) {
    
    this.codeStructure = codeStructure;
    return this;
  }

   /**
   * Le code interne de l&#39;établissement pour lequel la modalité de paiement sera créée
   * @return codeStructure
  **/
  @ApiModelProperty(required = true, value = "Le code interne de l'établissement pour lequel la modalité de paiement sera créée")

  public String getCodeStructure() {
    return codeStructure;
  }


  public void setCodeStructure(String codeStructure) {
    this.codeStructure = codeStructure;
  }


  public ModaliteDePaiement libelleAffichage(String libelleAffichage) {
    
    this.libelleAffichage = libelleAffichage;
    return this;
  }

   /**
   * Le libellé d&#39;affichage
   * @return libelleAffichage
  **/
  @ApiModelProperty(required = true, value = "Le libellé d'affichage")

  public String getLibelleAffichage() {
    return libelleAffichage;
  }


  public void setLibelleAffichage(String libelleAffichage) {
    this.libelleAffichage = libelleAffichage;
  }


  public ModaliteDePaiement codeModeDePaiement(String codeModeDePaiement) {
    
    this.codeModeDePaiement = codeModeDePaiement;
    return this;
  }

   /**
   * Code issu de la nomenclature mode de paiement du référentiel
   * @return codeModeDePaiement
  **/
  @ApiModelProperty(required = true, value = "Code issu de la nomenclature mode de paiement du référentiel")

  public String getCodeModeDePaiement() {
    return codeModeDePaiement;
  }


  public void setCodeModeDePaiement(String codeModeDePaiement) {
    this.codeModeDePaiement = codeModeDePaiement;
  }


  public ModaliteDePaiement temoinVisibleEtudiant(Boolean temoinVisibleEtudiant) {
    
    this.temoinVisibleEtudiant = temoinVisibleEtudiant;
    return this;
  }

   /**
   * Le témoin indiquant que cette modalité de paiement est proposée aux étudiants
   * @return temoinVisibleEtudiant
  **/
  @ApiModelProperty(required = true, value = "Le témoin indiquant que cette modalité de paiement est proposée aux étudiants")

  public Boolean getTemoinVisibleEtudiant() {
    return temoinVisibleEtudiant;
  }


  public void setTemoinVisibleEtudiant(Boolean temoinVisibleEtudiant) {
    this.temoinVisibleEtudiant = temoinVisibleEtudiant;
  }


  public ModaliteDePaiement statutPaiement(StatutPaiementEnum statutPaiement) {
    
    this.statutPaiement = statutPaiement;
    return this;
  }

   /**
   * Statut du paiement généré à la confirmation du paiement
   * @return statutPaiement
  **/
  @ApiModelProperty(required = true, value = "Statut du paiement généré à la confirmation du paiement")

  public StatutPaiementEnum getStatutPaiement() {
    return statutPaiement;
  }


  public void setStatutPaiement(StatutPaiementEnum statutPaiement) {
    this.statutPaiement = statutPaiement;
  }


  public ModaliteDePaiement temoinPrimo(Boolean temoinPrimo) {
    
    this.temoinPrimo = temoinPrimo;
    return this;
  }

   /**
   * Le témoin modalité de paiement proposée aux primo-entrants
   * @return temoinPrimo
  **/
  @ApiModelProperty(required = true, value = "Le témoin modalité de paiement proposée aux primo-entrants")

  public Boolean getTemoinPrimo() {
    return temoinPrimo;
  }


  public void setTemoinPrimo(Boolean temoinPrimo) {
    this.temoinPrimo = temoinPrimo;
  }


  public ModaliteDePaiement temoinReins(Boolean temoinReins) {
    
    this.temoinReins = temoinReins;
    return this;
  }

   /**
   * Le témoin modalité de paiement proposée lors de la réinscription
   * @return temoinReins
  **/
  @ApiModelProperty(required = true, value = "Le témoin modalité de paiement proposée lors de la réinscription")

  public Boolean getTemoinReins() {
    return temoinReins;
  }


  public void setTemoinReins(Boolean temoinReins) {
    this.temoinReins = temoinReins;
  }


  public ModaliteDePaiement nombreDePaiements(Integer nombreDePaiements) {
    
    this.nombreDePaiements = nombreDePaiements;
    return this;
  }

   /**
   * Le nombre de paiements
   * @return nombreDePaiements
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le nombre de paiements")

  public Integer getNombreDePaiements() {
    return nombreDePaiements;
  }


  public void setNombreDePaiements(Integer nombreDePaiements) {
    this.nombreDePaiements = nombreDePaiements;
  }


  public ModaliteDePaiement montantMinimum(BigDecimal montantMinimum) {
    
    this.montantMinimum = montantMinimum;
    return this;
  }

   /**
   * Le montant minimum pour proposer la modalité de paiement
   * @return montantMinimum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le montant minimum pour proposer la modalité de paiement")

  public BigDecimal getMontantMinimum() {
    return montantMinimum;
  }


  public void setMontantMinimum(BigDecimal montantMinimum) {
    this.montantMinimum = montantMinimum;
  }


  public ModaliteDePaiement montantMaximum(BigDecimal montantMaximum) {
    
    this.montantMaximum = montantMaximum;
    return this;
  }

   /**
   * Le montant maximum pour proposer la modalité de paiement
   * @return montantMaximum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le montant maximum pour proposer la modalité de paiement")

  public BigDecimal getMontantMaximum() {
    return montantMaximum;
  }


  public void setMontantMaximum(BigDecimal montantMaximum) {
    this.montantMaximum = montantMaximum;
  }


  public ModaliteDePaiement temoinSaisieReference(Boolean temoinSaisieReference) {
    
    this.temoinSaisieReference = temoinSaisieReference;
    return this;
  }

   /**
   * Le témoin de saisie d&#39;un motif ou d&#39;une référence
   * @return temoinSaisieReference
  **/
  @ApiModelProperty(required = true, value = "Le témoin de saisie d'un motif ou d'une référence")

  public Boolean getTemoinSaisieReference() {
    return temoinSaisieReference;
  }


  public void setTemoinSaisieReference(Boolean temoinSaisieReference) {
    this.temoinSaisieReference = temoinSaisieReference;
  }


   /**
   * Le témoin de paiement en ligne − ne sera pas pris en compte à la création ou la modification
   * @return temoinPaiementEnLigne
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Le témoin de paiement en ligne − ne sera pas pris en compte à la création ou la modification")

  public Boolean getTemoinPaiementEnLigne() {
    return temoinPaiementEnLigne;
  }




  public ModaliteDePaiement dateDebutValidite(String dateDebutValidite) {
    
    this.dateDebutValidite = dateDebutValidite;
    return this;
  }

   /**
   * La date de début de validité
   * @return dateDebutValidite
  **/
  @ApiModelProperty(required = true, value = "La date de début de validité")

  public String getDateDebutValidite() {
    return dateDebutValidite;
  }


  public void setDateDebutValidite(String dateDebutValidite) {
    this.dateDebutValidite = dateDebutValidite;
  }


  public ModaliteDePaiement dateFinValidite(String dateFinValidite) {
    
    this.dateFinValidite = dateFinValidite;
    return this;
  }

   /**
   * La date de fin de validité
   * @return dateFinValidite
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "La date de fin de validité")

  public String getDateFinValidite() {
    return dateFinValidite;
  }


  public void setDateFinValidite(String dateFinValidite) {
    this.dateFinValidite = dateFinValidite;
  }


  public ModaliteDePaiement prioriteAffichage(Integer prioriteAffichage) {
    
    this.prioriteAffichage = prioriteAffichage;
    return this;
  }

   /**
   * La priorité d&#39;affichage
   * @return prioriteAffichage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "La priorité d'affichage")

  public Integer getPrioriteAffichage() {
    return prioriteAffichage;
  }


  public void setPrioriteAffichage(Integer prioriteAffichage) {
    this.prioriteAffichage = prioriteAffichage;
  }


  public ModaliteDePaiement notice(String notice) {
    
    this.notice = notice;
    return this;
  }

   /**
   * Notice de la modalité de paiement
   * @return notice
  **/
  @ApiModelProperty(required = true, value = "Notice de la modalité de paiement")

  public String getNotice() {
    return notice;
  }


  public void setNotice(String notice) {
    this.notice = notice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModaliteDePaiement modaliteDePaiement = (ModaliteDePaiement) o;
    return Objects.equals(this.code, modaliteDePaiement.code) &&
        Objects.equals(this.codeStructure, modaliteDePaiement.codeStructure) &&
        Objects.equals(this.libelleAffichage, modaliteDePaiement.libelleAffichage) &&
        Objects.equals(this.codeModeDePaiement, modaliteDePaiement.codeModeDePaiement) &&
        Objects.equals(this.temoinVisibleEtudiant, modaliteDePaiement.temoinVisibleEtudiant) &&
        Objects.equals(this.statutPaiement, modaliteDePaiement.statutPaiement) &&
        Objects.equals(this.temoinPrimo, modaliteDePaiement.temoinPrimo) &&
        Objects.equals(this.temoinReins, modaliteDePaiement.temoinReins) &&
        Objects.equals(this.nombreDePaiements, modaliteDePaiement.nombreDePaiements) &&
        Objects.equals(this.montantMinimum, modaliteDePaiement.montantMinimum) &&
        Objects.equals(this.montantMaximum, modaliteDePaiement.montantMaximum) &&
        Objects.equals(this.temoinSaisieReference, modaliteDePaiement.temoinSaisieReference) &&
        Objects.equals(this.temoinPaiementEnLigne, modaliteDePaiement.temoinPaiementEnLigne) &&
        Objects.equals(this.dateDebutValidite, modaliteDePaiement.dateDebutValidite) &&
        Objects.equals(this.dateFinValidite, modaliteDePaiement.dateFinValidite) &&
        Objects.equals(this.prioriteAffichage, modaliteDePaiement.prioriteAffichage) &&
        Objects.equals(this.notice, modaliteDePaiement.notice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, codeStructure, libelleAffichage, codeModeDePaiement, temoinVisibleEtudiant, statutPaiement, temoinPrimo, temoinReins, nombreDePaiements, montantMinimum, montantMaximum, temoinSaisieReference, temoinPaiementEnLigne, dateDebutValidite, dateFinValidite, prioriteAffichage, notice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModaliteDePaiement {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    codeStructure: ").append(toIndentedString(codeStructure)).append("\n");
    sb.append("    libelleAffichage: ").append(toIndentedString(libelleAffichage)).append("\n");
    sb.append("    codeModeDePaiement: ").append(toIndentedString(codeModeDePaiement)).append("\n");
    sb.append("    temoinVisibleEtudiant: ").append(toIndentedString(temoinVisibleEtudiant)).append("\n");
    sb.append("    statutPaiement: ").append(toIndentedString(statutPaiement)).append("\n");
    sb.append("    temoinPrimo: ").append(toIndentedString(temoinPrimo)).append("\n");
    sb.append("    temoinReins: ").append(toIndentedString(temoinReins)).append("\n");
    sb.append("    nombreDePaiements: ").append(toIndentedString(nombreDePaiements)).append("\n");
    sb.append("    montantMinimum: ").append(toIndentedString(montantMinimum)).append("\n");
    sb.append("    montantMaximum: ").append(toIndentedString(montantMaximum)).append("\n");
    sb.append("    temoinSaisieReference: ").append(toIndentedString(temoinSaisieReference)).append("\n");
    sb.append("    temoinPaiementEnLigne: ").append(toIndentedString(temoinPaiementEnLigne)).append("\n");
    sb.append("    dateDebutValidite: ").append(toIndentedString(dateDebutValidite)).append("\n");
    sb.append("    dateFinValidite: ").append(toIndentedString(dateFinValidite)).append("\n");
    sb.append("    prioriteAffichage: ").append(toIndentedString(prioriteAffichage)).append("\n");
    sb.append("    notice: ").append(toIndentedString(notice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

