/*
 * Swagger Gestion - INS
 * Il s'agit de l'API de gestion - INS.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.model.insgestion;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * L&#39;état de la pièce
 */
@JsonAdapter(StatutPiece.Adapter.class)
public enum StatutPiece {
  
  ATTENDU("attendu"),
  
  CHARGE("charge"),
  
  REJETE("rejete"),
  
  VALIDE("valide");

  private String value;

  StatutPiece(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StatutPiece fromValue(String value) {
    for (StatutPiece b : StatutPiece.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<StatutPiece> {
    @Override
    public void write(final JsonWriter jsonWriter, final StatutPiece enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public StatutPiece read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return StatutPiece.fromValue(value);
    }
  }
}

