/*
 * IDT V1 
 *  # Introduction  Liste l'ensemble des services et des opérations disponibles dans le module IDT  Description service IDT  # Gestion des erreurs  ## StatusCode  | Code    | Description                                | |---------|--------------------------------------------| | 200     | Opération effectuée                        | |         | Cas particulier: Dans le cas d'APIs de     | |         | type bulk, un 200 peut aussi être retourné | |         | si des données de la requête sont          | |         | considérées en erreur                      | | 201     | Ressource créée                            | | 400     | Données envoyées par le client invalides   | | 403     | Accès refusé                               | | 404     | Ressource inexistante                      | | 409     | donnée déjà existante                      | | 500     | Erreur technique rencontrée par le serveur |   ## Codes d'erreurs  | Code      | Description                                | |-----------|--------------------------------------------| | notNull   | la propriété est obligatoire               | | notBlank  | la propriété ne doit pas être vide         | | size      | la longueur de la propriété est invalide   | | pattern   | les caractères ou la syntaxe de            | |           | la propriété est invalide                  | 
 *
 * The version of the OpenAPI document: 1.0.0-rc.20250415115823
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.univlorraine.pegase.idt.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * DonneesContact
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-28T10:08:07.402704300+02:00[Europe/Paris]")
public class DonneesContact {
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_PAYS = "adressePeriodeUPays";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE1_ETAGE = "adressePeriodeULigne1Etage";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE2_BATIMENT = "adressePeriodeULigne2Batiment";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE3_VOIE = "adressePeriodeULigne3Voie";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE4_COMPLEMENT = "adressePeriodeULigne4Complement";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_CODE_POSTAL = "adressePeriodeUCodePostal";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_CODE_COMMUNE = "adressePeriodeUCodeCommune";
  public static final String SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE5_ETRANGER = "adressePeriodeULigne5Etranger";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_PAYS = "adresseFixePays";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_LIGNE1_ETAGE = "adresseFixeLigne1Etage";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_LIGNE2_BATIMENT = "adresseFixeLigne2Batiment";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_LIGNE3_VOIE = "adresseFixeLigne3Voie";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_LIGNE4_COMPLEMENT = "adresseFixeLigne4Complement";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_CODE_POSTAL = "adresseFixeCodePostal";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_CODE_COMMUNE = "adresseFixeCodeCommune";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_LIGNE5_ETRANGER = "adresseFixeLigne5Etranger";
  public static final String SERIALIZED_NAME_ADRESSE_FIXE_PROPRIETAIRE = "adresseFixeProprietaire";
  public static final String SERIALIZED_NAME_TELEPHONE_CONTACT_URGENCE = "telephoneContactUrgence";
  public static final String SERIALIZED_NAME_TELEPHONE_CONTACT_URGENCE_PROPRIETAIRE = "telephoneContactUrgenceProprietaire";
  public static final String SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_INSTITUTIONNELLE = "adresseElectroniqueInstitutionnelle";
  public static final String SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_SECOURS = "adresseElectroniqueSecours";
  public static final String SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_SECOURS_PROPRIETAIRE = "adresseElectroniqueSecoursProprietaire";
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_PAYS)
  private PaysEtNationalites adressePeriodeUPays;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE1_ETAGE)
  private String adressePeriodeULigne1Etage;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE2_BATIMENT)
  private String adressePeriodeULigne2Batiment;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE3_VOIE)
  private String adressePeriodeULigne3Voie;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE4_COMPLEMENT)
  private String adressePeriodeULigne4Complement;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_CODE_POSTAL)
  private String adressePeriodeUCodePostal;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_CODE_COMMUNE)
  private String adressePeriodeUCodeCommune;
  @SerializedName(SERIALIZED_NAME_ADRESSE_PERIODE_U_LIGNE5_ETRANGER)
  private String adressePeriodeULigne5Etranger;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_PAYS)
  private PaysEtNationalites adresseFixePays;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_LIGNE1_ETAGE)
  private String adresseFixeLigne1Etage;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_LIGNE2_BATIMENT)
  private String adresseFixeLigne2Batiment;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_LIGNE3_VOIE)
  private String adresseFixeLigne3Voie;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_LIGNE4_COMPLEMENT)
  private String adresseFixeLigne4Complement;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_CODE_POSTAL)
  private String adresseFixeCodePostal;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_CODE_COMMUNE)
  private String adresseFixeCodeCommune;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_LIGNE5_ETRANGER)
  private String adresseFixeLigne5Etranger;
  @SerializedName(SERIALIZED_NAME_ADRESSE_FIXE_PROPRIETAIRE)
  private String adresseFixeProprietaire;
  @SerializedName(SERIALIZED_NAME_TELEPHONE_CONTACT_URGENCE)
  private String telephoneContactUrgence;
  @SerializedName(SERIALIZED_NAME_TELEPHONE_CONTACT_URGENCE_PROPRIETAIRE)
  private String telephoneContactUrgenceProprietaire;
  @SerializedName(SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_INSTITUTIONNELLE)
  private String adresseElectroniqueInstitutionnelle;
  @SerializedName(SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_SECOURS)
  private String adresseElectroniqueSecours;
  @SerializedName(SERIALIZED_NAME_ADRESSE_ELECTRONIQUE_SECOURS_PROPRIETAIRE)
  private String adresseElectroniqueSecoursProprietaire;

  public DonneesContact() { 
  }

  public DonneesContact adressePeriodeUPays(PaysEtNationalites adressePeriodeUPays) {
    
    this.adressePeriodeUPays = adressePeriodeUPays;
    return this;
  }

   /**
   * Get adressePeriodeUPays
   * @return adressePeriodeUPays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaysEtNationalites getAdressePeriodeUPays() {
    return adressePeriodeUPays;
  }


  public void setAdressePeriodeUPays(PaysEtNationalites adressePeriodeUPays) {
    this.adressePeriodeUPays = adressePeriodeUPays;
  }


  public DonneesContact adressePeriodeULigne1Etage(String adressePeriodeULigne1Etage) {
    
    this.adressePeriodeULigne1Etage = adressePeriodeULigne1Etage;
    return this;
  }

   /**
   * Ligne d&#39;adresse 1 (étage) durant le période universitaire
   * @return adressePeriodeULigne1Etage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 1 (étage) durant le période universitaire")

  public String getAdressePeriodeULigne1Etage() {
    return adressePeriodeULigne1Etage;
  }


  public void setAdressePeriodeULigne1Etage(String adressePeriodeULigne1Etage) {
    this.adressePeriodeULigne1Etage = adressePeriodeULigne1Etage;
  }


  public DonneesContact adressePeriodeULigne2Batiment(String adressePeriodeULigne2Batiment) {
    
    this.adressePeriodeULigne2Batiment = adressePeriodeULigne2Batiment;
    return this;
  }

   /**
   * Ligne d&#39;adresse 2 (bâtiment) durant le période universitaire
   * @return adressePeriodeULigne2Batiment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 2 (bâtiment) durant le période universitaire")

  public String getAdressePeriodeULigne2Batiment() {
    return adressePeriodeULigne2Batiment;
  }


  public void setAdressePeriodeULigne2Batiment(String adressePeriodeULigne2Batiment) {
    this.adressePeriodeULigne2Batiment = adressePeriodeULigne2Batiment;
  }


  public DonneesContact adressePeriodeULigne3Voie(String adressePeriodeULigne3Voie) {
    
    this.adressePeriodeULigne3Voie = adressePeriodeULigne3Voie;
    return this;
  }

   /**
   * Ligne d&#39;adresse 3 (voie) durant le période universitaire
   * @return adressePeriodeULigne3Voie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 3 (voie) durant le période universitaire")

  public String getAdressePeriodeULigne3Voie() {
    return adressePeriodeULigne3Voie;
  }


  public void setAdressePeriodeULigne3Voie(String adressePeriodeULigne3Voie) {
    this.adressePeriodeULigne3Voie = adressePeriodeULigne3Voie;
  }


  public DonneesContact adressePeriodeULigne4Complement(String adressePeriodeULigne4Complement) {
    
    this.adressePeriodeULigne4Complement = adressePeriodeULigne4Complement;
    return this;
  }

   /**
   * Ligne d&#39;adresse 4 (complément) durant le période universitaire
   * @return adressePeriodeULigne4Complement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 4 (complément) durant le période universitaire")

  public String getAdressePeriodeULigne4Complement() {
    return adressePeriodeULigne4Complement;
  }


  public void setAdressePeriodeULigne4Complement(String adressePeriodeULigne4Complement) {
    this.adressePeriodeULigne4Complement = adressePeriodeULigne4Complement;
  }


  public DonneesContact adressePeriodeUCodePostal(String adressePeriodeUCodePostal) {
    
    this.adressePeriodeUCodePostal = adressePeriodeUCodePostal;
    return this;
  }

   /**
   * Code postal durant le période universitaire
   * @return adressePeriodeUCodePostal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code postal durant le période universitaire")

  public String getAdressePeriodeUCodePostal() {
    return adressePeriodeUCodePostal;
  }


  public void setAdressePeriodeUCodePostal(String adressePeriodeUCodePostal) {
    this.adressePeriodeUCodePostal = adressePeriodeUCodePostal;
  }


  public DonneesContact adressePeriodeUCodeCommune(String adressePeriodeUCodeCommune) {
    
    this.adressePeriodeUCodeCommune = adressePeriodeUCodeCommune;
    return this;
  }

   /**
   * Code INSEE de la commune durant le période universitaire
   * @return adressePeriodeUCodeCommune
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code INSEE de la commune durant le période universitaire")

  public String getAdressePeriodeUCodeCommune() {
    return adressePeriodeUCodeCommune;
  }


  public void setAdressePeriodeUCodeCommune(String adressePeriodeUCodeCommune) {
    this.adressePeriodeUCodeCommune = adressePeriodeUCodeCommune;
  }


  public DonneesContact adressePeriodeULigne5Etranger(String adressePeriodeULigne5Etranger) {
    
    this.adressePeriodeULigne5Etranger = adressePeriodeULigne5Etranger;
    return this;
  }

   /**
   * Code postal pour ville étrangère durant le période universitaire
   * @return adressePeriodeULigne5Etranger
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code postal pour ville étrangère durant le période universitaire")

  public String getAdressePeriodeULigne5Etranger() {
    return adressePeriodeULigne5Etranger;
  }


  public void setAdressePeriodeULigne5Etranger(String adressePeriodeULigne5Etranger) {
    this.adressePeriodeULigne5Etranger = adressePeriodeULigne5Etranger;
  }


  public DonneesContact adresseFixePays(PaysEtNationalites adresseFixePays) {
    
    this.adresseFixePays = adresseFixePays;
    return this;
  }

   /**
   * Get adresseFixePays
   * @return adresseFixePays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PaysEtNationalites getAdresseFixePays() {
    return adresseFixePays;
  }


  public void setAdresseFixePays(PaysEtNationalites adresseFixePays) {
    this.adresseFixePays = adresseFixePays;
  }


  public DonneesContact adresseFixeLigne1Etage(String adresseFixeLigne1Etage) {
    
    this.adresseFixeLigne1Etage = adresseFixeLigne1Etage;
    return this;
  }

   /**
   * Ligne d&#39;adresse 1 (étage) hors période universitaire
   * @return adresseFixeLigne1Etage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 1 (étage) hors période universitaire")

  public String getAdresseFixeLigne1Etage() {
    return adresseFixeLigne1Etage;
  }


  public void setAdresseFixeLigne1Etage(String adresseFixeLigne1Etage) {
    this.adresseFixeLigne1Etage = adresseFixeLigne1Etage;
  }


  public DonneesContact adresseFixeLigne2Batiment(String adresseFixeLigne2Batiment) {
    
    this.adresseFixeLigne2Batiment = adresseFixeLigne2Batiment;
    return this;
  }

   /**
   * Ligne d&#39;adresse 2 (bâtiment) hors période universitaire
   * @return adresseFixeLigne2Batiment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 2 (bâtiment) hors période universitaire")

  public String getAdresseFixeLigne2Batiment() {
    return adresseFixeLigne2Batiment;
  }


  public void setAdresseFixeLigne2Batiment(String adresseFixeLigne2Batiment) {
    this.adresseFixeLigne2Batiment = adresseFixeLigne2Batiment;
  }


  public DonneesContact adresseFixeLigne3Voie(String adresseFixeLigne3Voie) {
    
    this.adresseFixeLigne3Voie = adresseFixeLigne3Voie;
    return this;
  }

   /**
   * Ligne d&#39;adresse 3 (voie) hors période universitaire
   * @return adresseFixeLigne3Voie
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 3 (voie) hors période universitaire")

  public String getAdresseFixeLigne3Voie() {
    return adresseFixeLigne3Voie;
  }


  public void setAdresseFixeLigne3Voie(String adresseFixeLigne3Voie) {
    this.adresseFixeLigne3Voie = adresseFixeLigne3Voie;
  }


  public DonneesContact adresseFixeLigne4Complement(String adresseFixeLigne4Complement) {
    
    this.adresseFixeLigne4Complement = adresseFixeLigne4Complement;
    return this;
  }

   /**
   * Ligne d&#39;adresse 4 (complément) hors période universitaire
   * @return adresseFixeLigne4Complement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Ligne d'adresse 4 (complément) hors période universitaire")

  public String getAdresseFixeLigne4Complement() {
    return adresseFixeLigne4Complement;
  }


  public void setAdresseFixeLigne4Complement(String adresseFixeLigne4Complement) {
    this.adresseFixeLigne4Complement = adresseFixeLigne4Complement;
  }


  public DonneesContact adresseFixeCodePostal(String adresseFixeCodePostal) {
    
    this.adresseFixeCodePostal = adresseFixeCodePostal;
    return this;
  }

   /**
   * Code postal hors période universitaire
   * @return adresseFixeCodePostal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code postal hors période universitaire")

  public String getAdresseFixeCodePostal() {
    return adresseFixeCodePostal;
  }


  public void setAdresseFixeCodePostal(String adresseFixeCodePostal) {
    this.adresseFixeCodePostal = adresseFixeCodePostal;
  }


  public DonneesContact adresseFixeCodeCommune(String adresseFixeCodeCommune) {
    
    this.adresseFixeCodeCommune = adresseFixeCodeCommune;
    return this;
  }

   /**
   * Code INSEE de la commune hors période universitaire
   * @return adresseFixeCodeCommune
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code INSEE de la commune hors période universitaire")

  public String getAdresseFixeCodeCommune() {
    return adresseFixeCodeCommune;
  }


  public void setAdresseFixeCodeCommune(String adresseFixeCodeCommune) {
    this.adresseFixeCodeCommune = adresseFixeCodeCommune;
  }


  public DonneesContact adresseFixeLigne5Etranger(String adresseFixeLigne5Etranger) {
    
    this.adresseFixeLigne5Etranger = adresseFixeLigne5Etranger;
    return this;
  }

   /**
   * Code postal pour ville étrangère hors période universitaire
   * @return adresseFixeLigne5Etranger
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code postal pour ville étrangère hors période universitaire")

  public String getAdresseFixeLigne5Etranger() {
    return adresseFixeLigne5Etranger;
  }


  public void setAdresseFixeLigne5Etranger(String adresseFixeLigne5Etranger) {
    this.adresseFixeLigne5Etranger = adresseFixeLigne5Etranger;
  }


  public DonneesContact adresseFixeProprietaire(String adresseFixeProprietaire) {
    
    this.adresseFixeProprietaire = adresseFixeProprietaire;
    return this;
  }

   /**
   * Proprietaire de la résendence hors période universitaire (exemple: Chez Mme XXXXXX)
   * @return adresseFixeProprietaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Proprietaire de la résendence hors période universitaire (exemple: Chez Mme XXXXXX)")

  public String getAdresseFixeProprietaire() {
    return adresseFixeProprietaire;
  }


  public void setAdresseFixeProprietaire(String adresseFixeProprietaire) {
    this.adresseFixeProprietaire = adresseFixeProprietaire;
  }


  public DonneesContact telephoneContactUrgence(String telephoneContactUrgence) {
    
    this.telephoneContactUrgence = telephoneContactUrgence;
    return this;
  }

   /**
   * Numéro de téléphone
   * @return telephoneContactUrgence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Numéro de téléphone")

  public String getTelephoneContactUrgence() {
    return telephoneContactUrgence;
  }


  public void setTelephoneContactUrgence(String telephoneContactUrgence) {
    this.telephoneContactUrgence = telephoneContactUrgence;
  }


  public DonneesContact telephoneContactUrgenceProprietaire(String telephoneContactUrgenceProprietaire) {
    
    this.telephoneContactUrgenceProprietaire = telephoneContactUrgenceProprietaire;
    return this;
  }

   /**
   * Nom et prénom de la personne à contacter en cas d&#39;urgence
   * @return telephoneContactUrgenceProprietaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Nom et prénom de la personne à contacter en cas d'urgence")

  public String getTelephoneContactUrgenceProprietaire() {
    return telephoneContactUrgenceProprietaire;
  }


  public void setTelephoneContactUrgenceProprietaire(String telephoneContactUrgenceProprietaire) {
    this.telephoneContactUrgenceProprietaire = telephoneContactUrgenceProprietaire;
  }


  public DonneesContact adresseElectroniqueInstitutionnelle(String adresseElectroniqueInstitutionnelle) {
    
    this.adresseElectroniqueInstitutionnelle = adresseElectroniqueInstitutionnelle;
    return this;
  }

   /**
   * Adresse électronique (Adresse email)
   * @return adresseElectroniqueInstitutionnelle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Adresse électronique (Adresse email)")

  public String getAdresseElectroniqueInstitutionnelle() {
    return adresseElectroniqueInstitutionnelle;
  }


  public void setAdresseElectroniqueInstitutionnelle(String adresseElectroniqueInstitutionnelle) {
    this.adresseElectroniqueInstitutionnelle = adresseElectroniqueInstitutionnelle;
  }


  public DonneesContact adresseElectroniqueSecours(String adresseElectroniqueSecours) {
    
    this.adresseElectroniqueSecours = adresseElectroniqueSecours;
    return this;
  }

   /**
   * Adresse électronique (Adresse email)
   * @return adresseElectroniqueSecours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Adresse électronique (Adresse email)")

  public String getAdresseElectroniqueSecours() {
    return adresseElectroniqueSecours;
  }


  public void setAdresseElectroniqueSecours(String adresseElectroniqueSecours) {
    this.adresseElectroniqueSecours = adresseElectroniqueSecours;
  }


  public DonneesContact adresseElectroniqueSecoursProprietaire(String adresseElectroniqueSecoursProprietaire) {
    
    this.adresseElectroniqueSecoursProprietaire = adresseElectroniqueSecoursProprietaire;
    return this;
  }

   /**
   * Nom et prénom de la personne propriétaire de l&#39;adresse mail de secours
   * @return adresseElectroniqueSecoursProprietaire
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Nom et prénom de la personne propriétaire de l'adresse mail de secours")

  public String getAdresseElectroniqueSecoursProprietaire() {
    return adresseElectroniqueSecoursProprietaire;
  }


  public void setAdresseElectroniqueSecoursProprietaire(String adresseElectroniqueSecoursProprietaire) {
    this.adresseElectroniqueSecoursProprietaire = adresseElectroniqueSecoursProprietaire;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DonneesContact donneesContact = (DonneesContact) o;
    return Objects.equals(this.adressePeriodeUPays, donneesContact.adressePeriodeUPays) &&
        Objects.equals(this.adressePeriodeULigne1Etage, donneesContact.adressePeriodeULigne1Etage) &&
        Objects.equals(this.adressePeriodeULigne2Batiment, donneesContact.adressePeriodeULigne2Batiment) &&
        Objects.equals(this.adressePeriodeULigne3Voie, donneesContact.adressePeriodeULigne3Voie) &&
        Objects.equals(this.adressePeriodeULigne4Complement, donneesContact.adressePeriodeULigne4Complement) &&
        Objects.equals(this.adressePeriodeUCodePostal, donneesContact.adressePeriodeUCodePostal) &&
        Objects.equals(this.adressePeriodeUCodeCommune, donneesContact.adressePeriodeUCodeCommune) &&
        Objects.equals(this.adressePeriodeULigne5Etranger, donneesContact.adressePeriodeULigne5Etranger) &&
        Objects.equals(this.adresseFixePays, donneesContact.adresseFixePays) &&
        Objects.equals(this.adresseFixeLigne1Etage, donneesContact.adresseFixeLigne1Etage) &&
        Objects.equals(this.adresseFixeLigne2Batiment, donneesContact.adresseFixeLigne2Batiment) &&
        Objects.equals(this.adresseFixeLigne3Voie, donneesContact.adresseFixeLigne3Voie) &&
        Objects.equals(this.adresseFixeLigne4Complement, donneesContact.adresseFixeLigne4Complement) &&
        Objects.equals(this.adresseFixeCodePostal, donneesContact.adresseFixeCodePostal) &&
        Objects.equals(this.adresseFixeCodeCommune, donneesContact.adresseFixeCodeCommune) &&
        Objects.equals(this.adresseFixeLigne5Etranger, donneesContact.adresseFixeLigne5Etranger) &&
        Objects.equals(this.adresseFixeProprietaire, donneesContact.adresseFixeProprietaire) &&
        Objects.equals(this.telephoneContactUrgence, donneesContact.telephoneContactUrgence) &&
        Objects.equals(this.telephoneContactUrgenceProprietaire, donneesContact.telephoneContactUrgenceProprietaire) &&
        Objects.equals(this.adresseElectroniqueInstitutionnelle, donneesContact.adresseElectroniqueInstitutionnelle) &&
        Objects.equals(this.adresseElectroniqueSecours, donneesContact.adresseElectroniqueSecours) &&
        Objects.equals(this.adresseElectroniqueSecoursProprietaire, donneesContact.adresseElectroniqueSecoursProprietaire);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adressePeriodeUPays, adressePeriodeULigne1Etage, adressePeriodeULigne2Batiment, adressePeriodeULigne3Voie, adressePeriodeULigne4Complement, adressePeriodeUCodePostal, adressePeriodeUCodeCommune, adressePeriodeULigne5Etranger, adresseFixePays, adresseFixeLigne1Etage, adresseFixeLigne2Batiment, adresseFixeLigne3Voie, adresseFixeLigne4Complement, adresseFixeCodePostal, adresseFixeCodeCommune, adresseFixeLigne5Etranger, adresseFixeProprietaire, telephoneContactUrgence, telephoneContactUrgenceProprietaire, adresseElectroniqueInstitutionnelle, adresseElectroniqueSecours, adresseElectroniqueSecoursProprietaire);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DonneesContact {\n");
    sb.append("    adressePeriodeUPays: ").append(toIndentedString(adressePeriodeUPays)).append("\n");
    sb.append("    adressePeriodeULigne1Etage: ").append(toIndentedString(adressePeriodeULigne1Etage)).append("\n");
    sb.append("    adressePeriodeULigne2Batiment: ").append(toIndentedString(adressePeriodeULigne2Batiment)).append("\n");
    sb.append("    adressePeriodeULigne3Voie: ").append(toIndentedString(adressePeriodeULigne3Voie)).append("\n");
    sb.append("    adressePeriodeULigne4Complement: ").append(toIndentedString(adressePeriodeULigne4Complement)).append("\n");
    sb.append("    adressePeriodeUCodePostal: ").append(toIndentedString(adressePeriodeUCodePostal)).append("\n");
    sb.append("    adressePeriodeUCodeCommune: ").append(toIndentedString(adressePeriodeUCodeCommune)).append("\n");
    sb.append("    adressePeriodeULigne5Etranger: ").append(toIndentedString(adressePeriodeULigne5Etranger)).append("\n");
    sb.append("    adresseFixePays: ").append(toIndentedString(adresseFixePays)).append("\n");
    sb.append("    adresseFixeLigne1Etage: ").append(toIndentedString(adresseFixeLigne1Etage)).append("\n");
    sb.append("    adresseFixeLigne2Batiment: ").append(toIndentedString(adresseFixeLigne2Batiment)).append("\n");
    sb.append("    adresseFixeLigne3Voie: ").append(toIndentedString(adresseFixeLigne3Voie)).append("\n");
    sb.append("    adresseFixeLigne4Complement: ").append(toIndentedString(adresseFixeLigne4Complement)).append("\n");
    sb.append("    adresseFixeCodePostal: ").append(toIndentedString(adresseFixeCodePostal)).append("\n");
    sb.append("    adresseFixeCodeCommune: ").append(toIndentedString(adresseFixeCodeCommune)).append("\n");
    sb.append("    adresseFixeLigne5Etranger: ").append(toIndentedString(adresseFixeLigne5Etranger)).append("\n");
    sb.append("    adresseFixeProprietaire: ").append(toIndentedString(adresseFixeProprietaire)).append("\n");
    sb.append("    telephoneContactUrgence: ").append(toIndentedString(telephoneContactUrgence)).append("\n");
    sb.append("    telephoneContactUrgenceProprietaire: ").append(toIndentedString(telephoneContactUrgenceProprietaire)).append("\n");
    sb.append("    adresseElectroniqueInstitutionnelle: ").append(toIndentedString(adresseElectroniqueInstitutionnelle)).append("\n");
    sb.append("    adresseElectroniqueSecours: ").append(toIndentedString(adresseElectroniqueSecours)).append("\n");
    sb.append("    adresseElectroniqueSecoursProprietaire: ").append(toIndentedString(adresseElectroniqueSecoursProprietaire)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

